version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - PATH=./node_modules/.bin:$PATH npm run build
artifacts:
  files:
    - build/**/*
  discard-paths: yes
