const images = [
  { src: '//unsplash.it/250/250', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/251', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/252', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/253', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/254', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/255', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/251/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/252/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/253/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/254/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/255/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/256/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/250', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/251', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/251/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/252/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/253/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/254/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/255/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/256/256', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/250', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/252', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/253', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/254', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/250', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/251', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/252', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/253', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/254', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/250', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/251', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/252', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/253', alt: 'Artist artwork.' },
  { src: '//unsplash.it/250/254', alt: 'Artist artwork.' },
];

export default images;
